# Docs https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "crates/cli",
  "crates/core",
  "crates/lua-frontend",
  "crates/make-frontend",
  "crates/utils"
]

[profile.release]
lto = true
