version: '3.7'
services:
  dev:
    build:
      context: .
      args:
        USER: ${USER:?USER environment variable must be set}
        UID: ${UID:?UID environment variable must be set}
    volumes:
      - ${WORKSPACE:?WORKSPACE environment variable must be set}:/home/${USER}/workspace
