[package]
name = "asmbl-core"
version = "0.1.0"
authors = ["Graham Rushton <gsrushton@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.6"
lazy_static = "1.4.0"
regex = "1"
shellwords = "1.0.0"
