[package]
name = "asmbl-make-frontend"
version = "0.1.0"
authors = ["Graham Rushton <gsrushton@gmail.com>"]
edition = "2018"

[dependencies]
asmbl-core = { path = "../../crates/core" }
asmbl-utils = { path = "../../crates/utils" }
failure = "0.1.6"
nom = "5"
