name: Main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: ./.github/actions/build
#      - name: Formatting
#        uses: actions-rs/cargo@v1
#        with:
#          command: fmt
#          args: --all -- --check
#      - name: Linting
#        uses: actions-rs/cargo@v1
#        with:
#          command: clippy
#          args: -- -D warnings
#
